from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# ── Enums ──────────────────────────────────────────────────────────────────────

class CampaignStatus(str, Enum):
    draft      = "draft"       # Just created — Gemini hasn't planned yet
    ready      = "ready"       # Gemini plan complete — posters not yet generated
    failed     = "failed"      # Gemini planning failed


# ── Nested ─────────────────────────────────────────────────────────────────────

class DayPlan(BaseModel):
    """One day's entry in the 5-day campaign plan returned by Gemini."""

    day:       int            = Field(..., ge=1, le=5, description="Day number (1 = Monday)")
    day_name:  str            = Field(..., description="e.g. Monday, Tuesday …")
    theme:     str            = Field(..., description="Daily theme generated by Gemini")
    poster_id: Optional[UUID] = Field(None, description="Null until poster is generated for this day")
    poll_id:   Optional[UUID] = Field(None, description="Null until poll is generated for this day")


# ── Requests ───────────────────────────────────────────────────────────────────

class CampaignCreate(BaseModel):
    """Request body for POST /campaigns/create."""

    topic:      str            = Field(..., min_length=3, max_length=200, description="Weekly campaign topic")
    objective:  str            = Field(..., min_length=3, max_length=500, description="Campaign objective / goal")
    session_id: Optional[UUID] = Field(None, description="Optional — auto-generated if not provided")


# ── Responses ──────────────────────────────────────────────────────────────────

class CampaignListItem(BaseModel):
    """Lightweight campaign entry for GET /campaigns list."""

    campaign_id: UUID
    topic:       str
    objective:   str
    status:      CampaignStatus
    created_at:  datetime

    model_config = {"from_attributes": True}


class CampaignResponse(BaseModel):
    """Full campaign detail for POST /campaigns/create and GET /campaigns/{id}."""

    campaign_id: UUID
    session_id:  UUID
    topic:       str
    objective:   str
    status:      CampaignStatus
    days:        list[DayPlan] = Field(default_factory=list)
    created_at:  datetime

    model_config = {"from_attributes": True}
